### ISSUE TITLE
docs for compiled modules contain all attributes

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocstrings/griffe#156] opened 2023-05-05 14:47 UTC
**Describe the bug**

When documenting [`pydantic_core/__init__.py`](https://github.com/pydantic/pydantic-core/blob/main/pydantic_core/__init__.py) which imports things from a compiled `.so` module `pydantic_core/_pydantic_core.so` [`.pyi` file](https://github.com/pydantic/pydantic-core/blob/main/pydantic_core/_pydantic_core.pyi), I see ever attribute being documented.

PR: https://github.com/pydantic/pydantic/pull/5695
preview build: https://smokeshow.helpmanual.io/5h320b176s5e5h5v0q1k/api/pydantic_core_init/

**To Reproduce**
1. clone pydantic-core
2. install recent rust with rustup
3. run `make install` to install deps and build pydantic-core
4. clone pydantic
5. `make install` to install deps
6. `pip install ../pydantic-core` to install pydantic-core
7. `mkdocs serve` to build and preview the docs

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
- `griffe` version: [e.g. 0.2.1] `griffe==0.27.1`
- Python version: [e.g. 3.8] 3.10.5
- OS: [Windows/Linux] MacOS m1

**Comment by pawamoy** [comment] 2023-05-05 16:09
What would like to get instead :smile:?

Try to use `filters` or `members` (see https://mkdocstrings.github.io/python/usage/#globallocal-options, better docs coming soon).

**Comment by samuelcolvin** [comment] 2023-05-05 23:27
I do have stubs - e.g. `.pyi` file, how do I only use that?

**Comment by pawamoy** [comment] 2023-05-06 12:13
I'll release a new version of the handler later that day and point you to the docs :slightly_smiling_face:

**Comment by samuelcolvin** [comment] 2023-05-06 12:55
Amazing

**Comment by pawamoy** [comment] 2023-05-06 22:41
Just released 0.10.0, the docs for `allow_inspection` are here: https://mkdocstrings.github.io/python/usage/configuration/general/#allow_inspection

**Comment by samuelcolvin** [comment] 2023-05-16 18:15
I've just tried this, I've tried defining each module attribute one by one, since `allow_inspection: false` shows nothing.

But either with

```
::: pydantic_core.PydanticOmit
    options:
      allow_inspection: false
```

I'm still seeing `with_traceback` documented:

![image](https://github.com/mkdocstrings/griffe/assets/4039449/a2651d6a-8380-492e-9d21-e814a5af2ad4)

**Comment by pawamoy** [comment] 2023-05-16 18:51
Yeah there's another issue saying that stubs are not picked up, I'll investigate. `filters` and `members should definitely work though.

**Comment by pawamoy** [comment] 2023-05-17 11:08
So, I've  tried to serve docs for pydantic, and setting `allow_inspection` to false seems to work fine. Stubs are correctly loaded. I indeed see nothing in http://localhost:8000/api/pydantic_core_init/ but that's because you don't have sufficient data in stubs, which is the expected behavior.

When I load pydantic through Griffe directly, disallowing inspection, and I resolve the alias to the `PydanticOmit` exception for example, Griffe only builds data for the `__init__` method of the exception, which is documented in a stub (`pydantic_core/_pydantic_core.pyi`), and doesn't have anything about base methods like `with_traceback` or `add_note`.

I'm gonna close this, but if you still encounter an issue with `allow_inspection`, please open a new issue with a MRE :slightly_smiling_face:

**Closed by pawamoy** 2023-05-17 11:08 UTC

**Comment by samuelcolvin** [comment] 2023-05-17 11:25
Thanks so much.
