### ISSUE TITLE
Recursion error with Griffe 0.33.0

### ISSUE THREAD

**Issue by Horytnik** [mkdocstrings/griffe#198] opened 2023-08-18 13:27 UTC
Hello, I am using mkdocs and with of its packages newest griffe is installed. I realized that I have recursion error during using it. 
to reproduce it just install mkdocs with Griffe at v0.33.0 and you will have recursion error 

![image](https://github.com/mkdocstrings/griffe/assets/52235355/a905c769-b687-47a2-852d-c742086a47af)

- `griffe` version: 0.33.0
- Python version: 3.8
- OS: Windows with WSL Ubuntu 20.04

Solution is to just force to install griffe 0.32.0 version

**Comment by pawamoy** [comment] 2023-08-18 13:40
Duplicate of https://github.com/mkdocstrings/griffe/issues/197 :slightly_smiling_face:

**Closed by pawamoy** 2023-08-18 13:40 UTC
