### ISSUE TITLE
RecursionError with Griffe, Material

### ISSUE THREAD

**Issue by Anatoly-Makarevich** [mkdocstrings/griffe#208] opened 2023-09-11 10:02 UTC
**Describe the bug**

Building mkdocstrings with Griffe>=0.33.0 fails with recursion error due to templates recursing.
Likely an issue between different plugins conflicting.

**Debug logs**
```console
$ mkdocs build -v
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/expression.html", line 1, in top-level template code
    {% extends "_base/expression.html" %}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/_base/expression.html", line 4, in top-level template code
    {%- include "expression.html" with context -%}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/expression.html", line 1, in top-level template code
    {% extends "_base/expression.html" %}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/_base/expression.html", line 4, in top-level template code
    {%- include "expression.html" with context -%}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/expression.html", line 1, in top-level template code
    {% extends "_base/expression.html" %}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/_base/expression.html", line 4, in top-level template code
    {%- include "expression.html" with context -%}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/expression.html", line 1, in top-level template code
    {% extends "_base/expression.html" %}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/mkdocstrings_handlers/python/templates/material/_base/expression.html", line 4, in top-level template code
    {%- include "expression.html" with context -%}
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/jinja2/utils.py", line 466, in get
    return self[key]
  File "/home/USERNAME/mambaforge/envs/ENVNAME/lib/python3.9/site-packages/jinja2/utils.py", line 508, in __getitem__
    self._remove(key)
RecursionError: maximum recursion depth exceeded in comparison
```

**To Reproduce**

**Expected behavior**

**System (please complete the following information):**
- `griffe` version: >=0.33.0
- Python version: 3.9.5
- OS: Ubuntu in WSL on Win 11 (but also others)

**Additional context**
Installed in mamba/conda environments.

Other library versions:
```
$ mamba list | grep mkdoc
mkdocs                    1.4.3                    pypi_0    pypi
mkdocs-autorefs           0.5.0                    pypi_0    pypi
mkdocs-click              0.8.0                    pypi_0    pypi
mkdocs-coverage           1.0.0                    pypi_0    pypi
mkdocs-jupyter            0.24.2                   pypi_0    pypi
mkdocs-material           9.1.2                    pypi_0    pypi
mkdocs-material-extensions 1.1.1                    pypi_0    pypi
mkdocs-monorepo-plugin    1.0.4                    pypi_0    pypi
mkdocs-techdocs-core      1.2.0                    pypi_0    pypi
mkdocstrings              0.20.0                   pypi_0    pypi
mkdocstrings-python       1.2.0                    pypi_0    pypi
```

I also tried removing `mkdocs-monorepo-plugin` and `mkdocs-techdocs-core` but they still failed.

**Comment by pawamoy** [comment] 2023-09-11 11:36
Probable duplicate of #197. See https://github.com/mkdocstrings/python/discussions/98 on how to resolve this (in short: upgrade mkdocstrings-python).

**Closed by pawamoy** 2023-09-11 11:36 UTC
