### ISSUE TITLE
Unable to see top-level imported functions on plotnine

### ISSUE THREAD

**Issue by machow** [mkdocstrings/griffe#176] opened 2023-06-29 15:21 UTC
**Describe the bug**

For the main branch of plotnine, functions are specified in `__all__`, but I can't seem to see them.

**To Reproduce**

```
# latest commit on main branch
pip install git+https://github.com/has2k1/plotnine.git@2405442dfd59f966ad98a6461ef870ea8e406235
```

```python
from griffe.loader import GriffeLoader

loader = GriffeLoader()

# Can't find geom_point at top-level ----

mod = loader.load_module("plotnine")
mod.members["geom_point"]      # KeyError


# Can find it in its submodule ----
mod2 = loader.load_module("plotnine.geoms.geom_point")
mod2.members["geom_point"]
```

**Expected behavior**

An Alias to `geom_point()` on the top-level module for `plotnine`

I'm happy to dig deeper, but am not sure where the error might be. Is there some part of a visitor that is failing silently? `plotnine` sometimes imports functions with the same names as modules, so I wonder if that is a factor here?

e.g. `geom_point()` lives in the module `plotnine.geoms.geom_point`. And uses imports that shadow (e.g. `from .geom_point import geom_point`).

**Comment by pawamoy** [comment] 2023-06-29 15:57
> plotnine sometimes imports functions with the same names as modules, so I wonder if that is a factor here?

Yep, definitely sounds like it's the cause. Since Griffe still suffers from the module/member-with-same-name issue, we avoid shadowing a module with an alias of the same name. However you should still see the `geom_point` module as a member of the `plotnine` one :thinking: Or maybe I misunderstood your modules layout. I'll check the plotnine repo and investigate :slightly_smiling_face:

**Comment by pawamoy** [comment] 2023-06-29 16:37
Ah wait, you simply need to resolve aliases:

```python
from griffe.loader import GriffeLoader

loader = GriffeLoader()
mod = loader.load_module("plotnine")
loader.resolve_aliases()
mod.members["geom_point"]      # found
```

**Comment by pawamoy** [comment] 2023-06-29 16:39
However it will an alias pointing to the `geom_point` module, not the `geom_point` function, because of the reasons mentioned above :confused:

**Comment by pawamoy** [comment] 2023-06-29 16:40
I should definitely add a `resolve_aliases` paramerer to `GriffeLoader.load_module` :thinking:

**Comment by machow** [comment] 2023-06-29 16:46
Ah, so close! Since `inspect()` is already dynamically importing `plotnine`, I don't mind adding a little logic to dynamically import the target (e.g. `from plotnine import geom_point`) and then use its `__module__` + `__qualname__` to grab it from its canonical path 🙃.

**Comment by pawamoy** [comment] 2023-06-29 16:58
Yeah the inspector surely works better in such cases. Closing then, the issue about module and member having the same name is well known and on my todo list :slightly_smiling_face:

**Closed by pawamoy** 2023-06-29 16:58 UTC
