### ISSUE TITLE
griffe.exceptions.AliasResolutionError: Could not resolve django.db.models.fields.json.JSONField

### ISSUE THREAD

**Issue by mRokita** [mkdocstrings/griffe#39] opened 2022-02-10 23:28 UTC
**Describe the bug**
The following exception is raised:

```pythontraceback
ERROR    -  Error building page 'reference/selectors/models.md': Could not resolve django.db.models.fields.json.JSONField
Traceback (most recent call last):
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 88, in get_item_url
    url = self._url_map[identifier]
KeyError: 'django.db.models.JSONField'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 864, in resolve_target
    resolved = self.modules_collection[self.target_path]
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/mixins.py", line 26, in __getitem__
    return self.members[parts[0]][parts[1]]  # type: ignore[attr-defined]
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/mixins.py", line 26, in __getitem__
    return self.members[parts[0]][parts[1]]  # type: ignore[attr-defined]
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/mixins.py", line 26, in __getitem__
    return self.members[parts[0]][parts[1]]  # type: ignore[attr-defined]
  [Previous line repeated 2 more times]
KeyError: 'json'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/myproject/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/myproject/.venv/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/myproject/.venv/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/myproject/.venv/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/myproject/.venv/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/myproject/.venv/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs/__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs/commands/build.py", line 314, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs/commands/build.py", line 220, in _build_page
    output = config['plugins'].run_event(
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 197, in on_post_page
    fixed_output, unmapped = fix_refs(output, url_mapper)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs_autorefs/references.py", line 186, in fix_refs
    html = AUTO_REF_RE.sub(fix_ref(url_mapper, unmapped), html)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs_autorefs/references.py", line 156, in inner
    url = url_mapper(unescape(identifier))
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocs_autorefs/plugin.py", line 94, in get_item_url
    new_identifiers = fallback(identifier)
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocstrings/handlers/base.py", line 408, in get_anchors
    anchors = handler.renderer.get_anchors(handler.collector.collect(identifier, fallback_config))
  File "/myproject/.venv/lib/python3.10/site-packages/mkdocstrings_handlers/python/collector.py", line 82, in collect
    if not just_loaded and doc_object.docstring is not None:
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 764, in __getattr__
    attr = getattr(self.target, name)
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 841, in target
    self.resolve_target()
  File "/myproject/.venv/lib/python3.10/site-packages/griffe/dataclasses.py", line 866, in resolve_target
    raise AliasResolutionError(self.target_path) from error
griffe.exceptions.AliasResolutionError: Could not resolve django.db.models.fields.json.JSONField
```

**To Reproduce**

Try to process the following code using mkdocstrings and griffe:
Raises exception `griffe.exceptions.AliasResolutionError`:

```python
from django.db import models

class CustomField(models.JSONField):
   ...
```

**Workaround**

```python
from django.db.models.fields.json import JSONField

class CustomField(JSONField):
   ...
```

**Expected behavior**

Should be processed normally

**System (please complete the following information):**
- `griffe` version: 0.11.6
- Python version: 3.10
- OS: Linux

**Additional context**

https://github.com/django/django/blob/main/django/db/models/__init__.py

**Comment by pawamoy** [comment] 2022-02-11 17:37
Hi @mRokita, thanks for the report! What version of the python handler do you have (mkdocstrings-python)?

**Comment by mRokita** [comment] 2022-02-11 18:39
Hi @pawamoy, thank you for creating this awesome tool :) 
According to my `poetry.lock` it's 0.5.3. I'm going to double check that on my PC later.

**Comment by pawamoy** [comment] 2022-02-11 19:52
I can't replicate :confused: 

```python
"""Testing Django models."""

from django.db import models


class CustomField(models.JSONField):
    """Docstring."""
```
![django](https://user-images.githubusercontent.com/3999221/153660083-76c1fc08-9859-4889-a7ab-92fc5534ccdb.png)

**Comment by pawamoy** [comment] 2022-02-13 13:46
Hmmm maybe the fix was not released after all. You can try again with 0.5.4 or 0.6.x (pushing new features in a few minutes).

**Comment by pawamoy** [comment] 2022-04-04 10:03
Closing for now, let me know if the issue is still here!

**Closed by pawamoy** 2022-04-04 10:03 UTC
